version: "3.8"

services:
  vote:
    image: voting-app:latest
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
     - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: worker-app:latest
    # Add any specific command or entrypoint if necessary

  db:
    image: postgres:9.4 # Consider using a newer version
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres" # Use secrets or environment variables for production

  result:
    image: result-app:latest
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      # Remove the debug port if not needed
      # - "5858:5858"

